CREATE TABLE `promo` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL DEFAULT '0',
	`text` TEXT NOT NULL,
	`start_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`stop_ts` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`isActive` TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
