CREATE TABLE `role` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(250) NULL DEFAULT NULL,
	`descr` TEXT NULL,
	`is_enabled` TINYINT(1) NULL DEFAULT '0',
	`is_deleted` TINYINT(1) NULL DEFAULT '0',
	`sys` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
