login_login_homepage:
    path:     /login
    defaults: { _controller: LoginLoginBundle:Default:index }

login_login_logout:
    path:     /logout
    defaults: { _controller: LoginLoginBundle:Default:logout }

admin_admin_homepage:
    path:     /admin
    defaults: { _controller: LoginLoginBundle:Admin:index}


admin_admin_hotels_edit:
    path:     /admin/hotels/{id}
    defaults: { _controller: LoginLoginBundle:Admin:edit}
    requirements:
        id: \d+

admin_admin_hotels_save:
    path:       /admin/hotels
    defaults:   { _controller: LoginLoginBundle:Admin:save}

admin_admin_hotels_del:
    path:       /admin/hotels/del/{id}
    defaults:   { _controller: LoginLoginBundle:Admin:del}
    requirements:
        id: \d+
